apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argo-cd
    server: 'https://kubernetes.default.svc'
  source:
    helm:
      releaseName: argo-cd
    repoURL: 'https://argoproj.github.io/argo-helm'
    targetRevision: 3.6.10
    chart: argo-cd
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
