apiVersion: v1
kind: Namespace
metadata:
  name: prometheus-stack

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: prometheus-stack

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: prometheus-stack

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 16.11.0
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: prometheusOperator.admissionWebhooks.failurePolicy
          value: Ignore
    chart: kube-prometheus-stack
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prometheus-stack
  syncPolicy:
    automated:
      selfHeal: true
